Feat/#0002 setup back
The-Bugger-Ducks/mood-hound-back pull request #5
Opened 2023-09-07 22:59 UTC by ThHenrique

# Título PR

## Issues relacionadas

#1 #3 

## PR Type

Que tipo de mudança a PR introduz?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Other... Please describe:

## Descreva a alteração

## Outras informações

2023-09-11 23:00 UTC, GabrielCamargoL approved these changes
parabéns, continue assim, que você irá decolar para outra galáxia :zap: :fire:  :rocket:  :+1:

2023-09-11 23:11 UTC, GabrielCamargoL requested changes

2023-09-11 23:11 UTC, GabrielCamargoL commented on src/modules/users/users.controller.ts
A tarefa #3 pede o restante do CRUD como listagem e edição de role, assim como o delete de usuário.
poderia ver isso, por favor?

2023-09-12 00:41 UTC, JoaoM-py approved these changes

2023-09-12 00:42 UTC, merged